version: '3.9'
services:
  nodeserver:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/home/app
    restart: always
    environment:
      - TZ=America/Caracas
      - DEBIAN_FRONTEND=noninteractive